version: "3"

networks:
  dbay:
    external: false

volumes:
  keycloak:
    driver: local
  mongo:
    driver: local

services:
  server1:
    image: backend
    build: ./backend
    environment:
      - MONGO_URL=mongodb://mongo
      - PROXY_KEYCLOAK_TO_LOCALHOST=true
    depends_on:
      - mongo
      - keycloak
    networks:
      - dbay
  server2:
    image: backend
    build: ./backend
    environment:
      - MONGO_URL=mongodb://mongo
      - PROXY_KEYCLOAK_TO_LOCALHOST=true
    depends_on:
      - mongo
      - keycloak
    networks:
      - dbay
  ui1:
    image: frontend
    build: ./frontend
    networks:
      - dbay
  ui2:
    image: frontend
    build: ./frontend
    networks:
      - dbay
  load_balancer:
    image: nginx_load_balancer
    build: ./nginx-load-balancer
    networks:
      - dbay
    ports:
      - "127.0.0.1:8080:80"
    depends_on:
      - ui1
      - ui2
      - server1
      - server2
  keycloak:
    image: keycloak-dbay
    build: ./keycloak-dbay
    container_name: keycloak
    environment:
      - KEYCLOAK_USER=${KEYCLOAK_USER}
      # NOTE: this is only for demonstration purposes
      # ordinarily, you should NOT embed passwords in files
      - KEYCLOAK_PASSWORD=${KEYCLOAK_PASSWORD}
    restart: always
    networks:
      - dbay
    volumes:
      - keycloak:/opt/jboss/keycloak/standalone/data
    ports:
      - "127.0.0.1:8081:8080"
  mongo:
    image: mongo:4
    container_name: mongo
    restart: always
    networks:
      - dbay
    volumes:
      - mongo:/data/db
    ports:
      - "127.0.0.1:27017:27017"