FROM keycloak18

WORKDIR /opt/jboss/keycloak/standalone/deployments
RUN curl https://repo1.maven.org/maven2/net/micedre/keycloak/keycloak-mail-whitelisting/1.5/keycloak-mail-whitelisting-1.5.jar --output keycloak-mail-whitelisting-1.5.jar
